### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by eshimischi**
UnoCSS 0.54

### CODE REVIEW

**Comment by eshimischi** [comment]
Still have no extra time to make it with Actions, but need to update my project right now with unocss 0.54

**Comment by StarLederer** [comment]
Thanks for the contribution! I can set up the actions myself but these actions would need to execute some sort of script that ensures everything still works, hopefully that makes it a bit easier if you find some time for it

**Comment by eshimischi** [comment]
Pity, don't have enough time for that, sorry. Would you please uprise package version to npm, thanks in advanced

**Comment by StarLederer** [comment]
New version is up

**Pull request merged**
